# Generated by Django 5.2.4 on 2025-07-17 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.make')),
            ],
            options={
                'unique_together': {('make', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CarConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.carmodel')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.make')),
            ],
            options={
                'ordering': ['make__name', 'model__name', 'year'],
                'unique_together': {('make', 'model', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TaskForConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.JSONField(help_text='A list of detailed steps for this specific car.')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.carconfiguration')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.maintenancetask')),
            ],
            options={
                'verbose_name_plural': 'Tasks for Configurations',
                'unique_together': {('task', 'configuration')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.carconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_performed', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.taskforconfiguration')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selectVehicle.vehicle')),
            ],
        ),
    ]
